---
kind: pipeline
type: docker
name: default

steps: 
- name: terrafrom init
  image: hashicorp/terraform
  environment:
    GOOGLE:
      from_secret: google_api_token
  commands:
  - terraform init
  - terraform plan -var-file=config.tfvars -var 'google_credentials=$GOOGLE'
- name: static code analysis with tflint
  image: wata727/tflint
  commands:
  - tflint