---
kind: pipeline
type: docker
name: default

steps: 
- name: terrafrom init
  image: hashicorp/terraform
  commands:
  - terraform init
- name: terrafrom validate
  image: hashicorp/terraform
  commands:
  - terraform validate
- name: terrafrom plan
  image: hashicorp/terraform
  commands:
  - terraform plan -var-file=config.tfvars
- name: static code analysis with tflint
  image: wata727/tflint
  commands:
  - tflint
- name: terrafrom apply
  image: hashicorp/terraform
  commands:
  - terraform apply -var-file=config.tfvars -auto-approve
- name: terrafrom output 
  image: hashicorp/terraform
  commands:
  - terraform output ips_appservers 
- name: terrafrom destroy appserver
  image: hashicorp/terraform
  commands:
  - terraform destroy -var-file=config.tfvars -auto-approve