---
kind: pipeline
type: docker
name: CI/CD Terraform validate and test Server

steps: 
- name: terrafrom init
  image: hashicorp/terraform
  commands:
  - terraform init
- name: validate configuration
  image: hashicorp/terraform
  commands:
  - terraform validate
- name: terrafrom plan
  image: hashicorp/terraform
  commands:
  - terraform plan -var-file=config.tfvars
- name: static code analysis tflint
  image: wata727/tflint
  commands:
  - tflint
- name: apply servers
  image: hashicorp/terraform
  commands:
  - terraform apply -var-file=config.tfvars -auto-approve
- name: terrafrom output 
  image: hashicorp/terraform
  commands:
  - terraform output ips_appservers 
- name: destroy servers
  image: hashicorp/terraform
  commands:
  - terraform destroy -var-file=config.tfvars -auto-approve